added new token Astrocoin for ASTROPOOL
cardano-foundation/cardano-token-registry pull request #179
Opened 2021-06-16 08:52 UTC by jrx-sjg

# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [X] Metadata related change
- [ ] Other

## Checklist:

- [X] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

2021-06-18 10:29 UTC, jrx-sjg commented
Please can someone review this PR? We need it for our marketing strategy.

2021-06-18 14:08 UTC, admin-cf requested changes
Hi jrx-sjg ,

Please resubmit without the "tool" field which is currently not supported

2021-06-19 09:29 UTC, jrx-sjg commented
> Hi jrx-sjg ,
> 
> Please resubmit without the "tool" field which is currently not supported

Hi, It's removed now.

2021-06-22 10:13 UTC, admin-cf approved these changes

2021-06-22 10:13 UTC, merged