Add token metadata for the Al Plastino Centennial Series
cardano-foundation/cardano-token-registry pull request #180
Opened 2021-06-16 23:45 UTC by A-Caccese

# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [x] Metadata related change
- [ ] Other

## Checklist:

- [x] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

2021-06-19 10:42 UTC, A-Caccese commented
@admin-cf can you please tell me what is wrong with this pull request?

2021-06-22 11:09 UTC, admin-cf requested changes
Hi A-Caccese,

We are not supporting batch submissions at present. Could you please break up your submission into 4 separate PR's, one for each record. thanks you.

2021-06-22 17:14 UTC, A-Caccese commented
> 
> 
> Hi A-Caccese,
> 
> We are not supporting batch submissions at present. Could you please break up your submission into 4 separate PR's, one for each record. thanks you.

I changed the commit to one file, thanks for your response.

2021-06-23 08:39 UTC, admin-cf approved these changes

2021-06-23 08:39 UTC, merged