Add files via upload
cardano-foundation/cardano-token-registry pull request #188
Opened 2021-06-20 20:05 UTC by KaizenCrypto

Kaizen Token Metadata

# Pull Request Template

## Description

Metadata change for Kaizen Token, including name, description, url, and png

## Type of change

- [x] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

2021-06-22 10:24 UTC, admin-cf requested changes
Hi KaizenCrypto ,

Please resubmit without the "tool" field which is currently not supported

2021-06-22 16:38 UTC, KaizenCrypto commented
Hello, 

Thank you for your response. File has been editted. "Tool" field has been removed.

2021-06-22 16:41 UTC, KaizenCrypto commented
Hi there,

File has been edited and resubmitted without the 'tool' field. Thank you
for your help.



On Tue, Jun 22, 2021 at 6:24 AM Cardano Foundation Team <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi KaizenCrypto ,
>
> Please resubmit without the "tool" field which is currently not supported
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cardano-foundation/cardano-token-registry/pull/188#pullrequestreview-689329154>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOVNLF7RUC4NBOKBG2CE5X3TUBQGFANCNFSM47AMAMPQ>
> .
>

2021-06-23 08:40 UTC, admin-cf approved these changes

2021-06-23 08:40 UTC, merged