Add MysteriousOrb
cardano-foundation/cardano-token-registry pull request #258
Opened 2021-07-23 00:13 UTC by Chris-Graffagnino

# Pull Request Template

## Description

Add Mysterious Orb token

## Type of change

- [x] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

2021-07-26 11:04 UTC, crptmppt requested changes
The automated checks are failing (seems to be due to sequence number not incremented).
Thanks for addressing so the PR can be merged.

2021-07-28 01:22 UTC, Chris-Graffagnino commented
@crptmppt  I have regenerated the metadata file to satisfy the automated checks. Thank you.

2021-07-28 05:14 UTC, crptmppt commented
@Chris-Graffagnino thanks - I can see they are passing - the mapping however has an additional 'tool' field which isn't part of the well-known properties. Thank you for removing it:  merging is currently limited to well-known metadata for now - this might change in the future, thank you for understanding!

2021-07-29 11:47 UTC, admin-cf approved these changes

2021-07-29 11:48 UTC, crptmppt approved these changes

2021-07-29 11:49 UTC, merged