harmlesscoin
cardano-foundation/cardano-token-registry pull request #288
Opened 2021-08-05 16:26 UTC by harmlesscoin

# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

2021-08-06 15:54 UTC, crptmppt requested changes
The mapping has one or more additional field which isn't part of the well-known properties. (`tool`) Thank you for removing it: merging is currently limited to well-known metadata for now - this might change in the future, thank you for understanding!

2021-08-06 17:50 UTC, crptmppt requested changes
It seems the CI is not passing now - there seems to be an error in the JSON format now. (look at the Checks tab for more details). Thanks for addressing!

2021-08-06 17:52 UTC, harmlesscoin commented
> It seems the CI is not passing now - there seems to be an error in the JSON format now. (look at the Checks tab for more details). Thanks for addressing!

Now changed what Checks tab says. So it must be good now.

2021-08-13 14:14 UTC, admin-cf approved these changes

2021-08-13 14:17 UTC, merged