BLACKBERRY TOKEN Submission
cardano-foundation/cardano-token-registry pull request #4088
Opened 2024-02-19 01:08 UTC by JIMER111

# Pull Request Template

## Description

Please BLACKBERRY approve many thanks !

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

2024-02-19 09:11 UTC, Kartiiyer12 commented
Hi @JIMER111 Please change the name and the tickr for the token so that it does not contain ADA in the name. AIADA will cause confusion and hence cannot be approved. Please change the name and resubmit the PR again.

2024-02-19 11:25 UTC, JIMER111 commented
I have followed your request. Thanks

Vào Th 2, 19 thg 2, 2024 vào lúc 16:11 Kartiiyer12 <
***@***.***> đã viết:

> Hi @JIMER111 <https://github.com/JIMER111> Please change the name and the
> tickr for the token so that it does not contain ADA in the name. AIADA will
> cause confusion and hence cannot be approved. Please change the name and
> resubmit the PR again.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/cardano-foundation/cardano-token-registry/pull/4088#issuecomment-1952004624>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BGHX27A2OFDCE4J3J7BJKLDYUMJNVAVCNFSM6AAAAABDOTIFL2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNJSGAYDINRSGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>

2024-02-20 19:08 UTC, Kartiiyer12 commented
Hi @JIMER111 
Once you change the JSON, the signature value will also change, Can you please sign the data again like you did for first commit so that the signature is proper.

2024-02-20 19:13 UTC, VladislavKudrin requested changes

2024-02-26 07:41 UTC, VladislavKudrin approved these changes

2024-02-26 07:41 UTC, merged